### ISSUE TITLE
Error while training Levenshtein Transformer for APE task (AssertionError: forward function only supports training)

### ISSUE THREAD

**Issue by abhishek0318** [zerocstaker/constrained_ape#1]
## Error while training Levenshtein Transformer for APE task

Hi, thanks for sharing this code!
I was trying to train Levenshtein transformer for APE task following the instructions [here](https://github.com/zerocstaker/constrained_ape#levenshtein-transformer-training-from-noisy_mt---target), but an error pops up (described below). Any pointers as to what may be causing this?

### To Reproduce

1. Preprocess the data. After preprocessing my data directory looks like this:

> abhishek@system: ls $TRAIN_DIR
> dict.pe.txt  dict.src.txt  train.mt.bin  train.mt.idx  train.pt.bin  train.pt.idx  train.src.bin  train.src.idx  valid.mt.bin  valid.mt.idx  valid.pt.bin  valid.pt.idx  valid.src.bin  valid.src.idx

2. Run the following command,

> fairseq-train \
>     $TRAIN_DIR \
>     --save-dir checkpoints/levenshtein_transformer_mt_prev_target \
>     --ddp-backend=no_c10d \
>     --task ape_lev \
>     --criterion nat_loss \
>     --arch levenshtein_transformer \
>     --noise random_delete \
>     --share-all-embeddings \
>     --optimizer adam --adam-betas '(0.9,0.98)' \
>     --lr 0.0005 --lr-scheduler inverse_sqrt \
>     --min-lr '1e-09' --warmup-updates 10000 \
>     --warmup-init-lr '1e-07' --label-smoothing 0.1 \
>     --dropout 0.3 --weight-decay 0.01 \
>     --decoder-learned-pos \
>     --encoder-learned-pos \
>     --apply-bert-init \
>     --fixed-validation-seed 7 \
>     --max-tokens 8000 --update-freq 8 \
>     --save-interval-updates 10000 --no-epoch-checkpoints \
>     --max-update 300000 --source-lang src --target-lang pe --fp16 \
>     --num-workers 16 --prev-target mt\
>

3. This error pops up:

```
2021-06-10 08:01:01 | INFO | fairseq_cli.train | Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9,0.98)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, all_gather_list_size=16384, apply_bert_init=True, arch='levenshtein_transformer', attention_dropout=0.0, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_suffix='', clip_norm=0.0, cpu=False, criterion='nat_loss', cross_self_attention=False, curriculum=0, data='data', data_buffer_size=10, dataset_impl=None, ddp_backend='no_c10d', decoder_attention_heads=8, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=2048, decoder_input_dim=512, decoder_layerdrop=0, decoder_layers=6, decoder_layers_to_keep=None, decoder_learned_pos=True, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', dropout=0.3, early_exit='6,6,6', empty_cache_freq=0, encoder_attention_heads=8, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_layerdrop=0, encoder_layers=6, encoder_layers_to_keep=None, encoder_learned_pos=True, encoder_normalize_before=False, eval_bleu=False, eval_bleu_args=None, eval_bleu_detok='space', eval_bleu_detok_args=None, eval_bleu_print_samples=False, eval_bleu_remove_bpe=None, eval_tokenized_bleu=False, fast_stat_sync=False, find_unused_parameters=False, fix_batches_to_gpus=False, fixed_validation_seed=7, fp16=True, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, init_output='blank', input_type='src-only', keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, label_smoothing=0.1, left_pad_source='True', left_pad_target='False', load_alignments=False, localsgd_frequency=3, log_format=None, log_interval=100, lr=[0.0005], lr_scheduler='inverse_sqrt', max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=8000, max_tokens_valid=8000, max_update=300000, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, model_parallel_size=1, no_cross_attention=False, no_epoch_checkpoints=True, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=True, no_share_discriminator=False, no_share_last_layer=False, no_share_maskpredictor=False, no_token_positional_embeddings=False, noise='random_delete', nprocs_per_node=1, num_batch_buckets=0, num_workers=16, optimizer='adam', optimizer_overrides='{}', patience=-1, prev_target='mt', profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sampling_for_deletion=False, save_dir='checkpoints/levenshtein_transformer_mt_prev_target', save_interval=1, save_interval_updates=10000, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, share_discriminator_maskpredictor=False, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, source_lang='src', target_lang='pe', task='ape_lev', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', truncate_source=False, update_freq=[8], upsample_primary=1, use_bmuf=False, use_old_adam=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_init_lr=1e-07, warmup_updates=10000, weight_decay=0.01)
2021-06-10 08:01:01 | INFO | fairseq.tasks.translation | [src] dictionary: 43968 types
2021-06-10 08:01:01 | INFO | fairseq.tasks.translation | [pe] dictionary: 43968 types
2021-06-10 08:01:01 | INFO | fairseq.data.data_utils | loaded 39742 examples from: data/valid.src
2021-06-10 08:01:01 | INFO | fairseq.data.data_utils | loaded 39742 examples from: data/valid.mt
2021-06-10 08:01:01 | INFO | fairseq.tasks.ape | data valid 39742 examples

...........

2021-06-10 08:01:04 | INFO | fairseq_cli.train | model levenshtein_transformer, criterion LabelSmoothedDualImitationCriterion
2021-06-10 08:01:04 | INFO | fairseq_cli.train | num. model params: 67963904 (num. trained: 67963904)
2021-06-10 08:01:08 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.embed_tokens.weight
2021-06-10 08:01:08 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.output_projection.weight
2021-06-10 08:01:08 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2021-06-10 08:01:08 | INFO | fairseq.utils | rank   0: capabilities =  7.0  ; total memory = 15.782 GB ; name = Tesla V100-SXM2-16GB
2021-06-10 08:01:08 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2021-06-10 08:01:08 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)
2021-06-10 08:01:08 | INFO | fairseq_cli.train | max tokens per GPU = 8000 and max sentences per GPU = None
2021-06-10 08:01:08 | INFO | fairseq.trainer | no existing checkpoint found checkpoints/levenshtein_transformer_mt_prev_target/checkpoint_last.pt
2021-06-10 08:01:08 | INFO | fairseq.trainer | loading train data for epoch 1
2021-06-10 08:01:09 | INFO | fairseq.data.data_utils | loaded 3934521 examples from: data/train.src
2021-06-10 08:01:09 | INFO | fairseq.data.data_utils | loaded 3934521 examples from: data/train.mt
2021-06-10 08:01:09 | INFO | fairseq.tasks.ape | data train1 3934521 examples
/home/ubuntu/constrained_ape/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py:477: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "/home/ubuntu/constrained_ape/venv/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/ubuntu/constrained_ape/fairseq_cli/train.py", line 366, in cli_main
    cli_main_helper(args)
  File "/home/ubuntu/constrained_ape/fairseq_cli/train.py", line 404, in cli_main_helper
    main(args)
  File "/home/ubuntu/constrained_ape/fairseq_cli/train.py", line 135, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/home/ubuntu/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/constrained_ape/fairseq_cli/train.py", line 226, in train
    log_output = trainer.train_step(samples)
  File "/home/ubuntu/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/constrained_ape/fairseq/trainer.py", line 421, in train_step
    ignore_grad=is_dummy_batch,
  File "/home/ubuntu/constrained_ape/fairseq/tasks/ape_lev.py", line 84, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/ubuntu/constrained_ape/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/constrained_ape/fairseq/criterions/nat_loss.py", line 97, in forward
    outputs = model(**{**sample['net_input'],**{'tgt_tokens':tgt_tokens,'prev_output_tokens':prev_output_tokens}})
  File "/home/ubuntu/constrained_ape/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/constrained_ape/fairseq/models/nat/levenshtein_transformer.py", line 81, in forward
    assert tgt_tokens is not None, "forward function only supports training."
AssertionError: forward function only supports training.
```

### Expected behavior

No Error

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): pip install --editable ./
 - Python version: 3.7.7

**Comment by abhishek0318** [comment]
Closing the issue. I had a bug in the preprocessing part. I was using the suffix `pt` instead of the suffix `pe`. The contents of the $TRAIN_DIR should look something like this,
> abhishek@system: ls $TRAIN_DIR
> dict.pe.txt   train.mt.idx  train.src.bin  valid.mt.idx  valid.src.bin
> dict.src.txt  train.pe.bin  train.src.idx  valid.pe.bin  valid.src.idx
> train.mt.bin  train.pe.idx  valid.mt.bin   valid.pe.idx
